# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designs/get_text_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 301)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(10)
        self.ok_btn.setFont(font)
        self.ok_btn.setStyleSheet("QPushButton {\n"
"                        background-color: #bcbcbc;\n"
"                        border-style: solid;\n"
"                        border-radius: 15px;\n"
"                    }\n"
"                    QPushButton:pressed {\n"
"                        background-color: #DDA0DD;\n"
"                        border-style: inset;\n"
"                    }")
        self.ok_btn.setObjectName("ok_btn")
        self.gridLayout.addWidget(self.ok_btn, 2, 0, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(10)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"                        background-color: #bcbcbc;\n"
"                        border-style: solid;\n"
"                        border-radius: 15px;\n"
"                    }\n"
"                    QPushButton:pressed {\n"
"                        background-color: #DDA0DD;\n"
"                        border-style: inset;\n"
"                    }")
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout.addWidget(self.cancel_btn, 2, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 2)
        self.text = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(10)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.gridLayout.addWidget(self.text, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ok_btn.setText(_translate("Dialog", "OK"))
        self.cancel_btn.setText(_translate("Dialog", "Отмена"))
        self.text.setText(_translate("Dialog", "TextLabel"))
