# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designs\player.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.music_list = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_list.sizePolicy().hasHeightForWidth())
        self.music_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(12)
        self.music_list.setFont(font)
        self.music_list.setStyleSheet("QListWidget\n"
"                        {\n"
"                            border : 1px solid black;\n"
"                            background : #eeeeee;\n"
"                            border-radius: 10px;\n"
"                                            }\n"
"                     QListWidget QScrollBar\n"
"                        {\n"
"                    background : #959995;\n"
"                        }\n"
"                            QListView::item:selected\n"
"                        {\n"
"                            border : 2px solid black;\n"
"                            background : #999999;\n"
"                        }")
        self.music_list.setObjectName("music_list")
        self.gridLayout.addWidget(self.music_list, 1, 0, 1, 5)
        self.music_duration = QtWidgets.QSlider(self.centralwidget)
        self.music_duration.setEnabled(False)
        self.music_duration.setStyleSheet("QSlider{\n"
"                                background: #E3DEE2;\n"
"                            }\n"
"                            QSlider::groove:horizontal {  \n"
"                                height: 10px;\n"
"                                margin: 0px;\n"
"                                border-radius: 5px;\n"
"                                background: #B0AEB1;\n"
"                            }\n"
"                            QSlider::handle:horizontal {\n"
"                                background: #fff;\n"
"                                border: 1px solid #E3DEE2;\n"
"                                width: 17px;\n"
"                                margin: -5px 0; \n"
"                                border-radius: 8px;\n"
"                            }\n"
"                            QSlider::sub-page:qlineargradient {\n"
"                                background: #000;\n"
"                                border-radius: 5px;\n"
"                            }")
        self.music_duration.setMaximum(9999)
        self.music_duration.setOrientation(QtCore.Qt.Horizontal)
        self.music_duration.setObjectName("music_duration")
        self.gridLayout.addWidget(self.music_duration, 3, 0, 1, 5)
        self.pause_btn = QtWidgets.QPushButton(self.centralwidget)
        self.pause_btn.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pause_btn.setFont(font)
        self.pause_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pause_btn.setStyleSheet("QPushButton {\n"
"                        background-color: #bcbcbc;\n"
"                        border-style: solid;\n"
"                        border-radius: 60px;\n"
"                    }\n"
"                    QPushButton:pressed {\n"
"                        background-color: #DDA0DD;\n"
"                        border-style: inset;\n"
"                    }\n"
"")
        self.pause_btn.setObjectName("pause_btn")
        self.gridLayout.addWidget(self.pause_btn, 2, 1, 1, 1)
        self.previous_btn = QtWidgets.QPushButton(self.centralwidget)
        self.previous_btn.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(20)
        self.previous_btn.setFont(font)
        self.previous_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previous_btn.setStyleSheet("QPushButton {\n"
"                        background-color: #bcbcbc;\n"
"                        border-style: solid;\n"
"                        border-radius: 60px;\n"
"                    }\n"
"                    QPushButton:pressed {\n"
"                        background-color: #DDA0DD;\n"
"                        border-style: inset;\n"
"                    }")
        self.previous_btn.setObjectName("previous_btn")
        self.gridLayout.addWidget(self.previous_btn, 2, 0, 1, 1)
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(20)
        self.play_btn.setFont(font)
        self.play_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_btn.setStyleSheet("QPushButton {\n"
"                        background-color: #bcbcbc;\n"
"                        border-style: solid;\n"
"                        border-radius: 60px;\n"
"                    }\n"
"                    QPushButton:pressed {\n"
"                        background-color: #DDA0DD;\n"
"                        border-style: inset;\n"
"                    }")
        self.play_btn.setObjectName("play_btn")
        self.gridLayout.addWidget(self.play_btn, 2, 2, 1, 1)
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        self.next_btn.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(20)
        self.next_btn.setFont(font)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setStyleSheet("QPushButton {\n"
"                        background-color: #bcbcbc;\n"
"                        border-style: solid;\n"
"                        border-radius: 60px;\n"
"                    }\n"
"                    QPushButton:pressed {\n"
"                        background-color: #DDA0DD;\n"
"                        border-style: inset;\n"
"                    }")
        self.next_btn.setObjectName("next_btn")
        self.gridLayout.addWidget(self.next_btn, 2, 3, 1, 1)
        self.get_track = QtWidgets.QPushButton(self.centralwidget)
        self.get_track.setMinimumSize(QtCore.QSize(0, 130))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.get_track.setFont(font)
        self.get_track.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_track.setStyleSheet("QPushButton {\n"
"                        background-color: #bcbcbc;\n"
"                        border-style: solid;\n"
"                        border-radius: 60px;\n"
"                    }\n"
"                    QPushButton:pressed {\n"
"                        background-color: #DDA0DD;\n"
"                        border-style: inset;\n"
"                    }\n"
"")
        self.get_track.setObjectName("get_track")
        self.gridLayout.addWidget(self.get_track, 2, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        self.playlist_menu = QtWidgets.QMenu(self.menubar)
        self.playlist_menu.setObjectName("playlist_menu")
        self.track_menu = QtWidgets.QMenu(self.menubar)
        self.track_menu.setObjectName("track_menu")
        self.add_menu = QtWidgets.QMenu(self.track_menu)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Typewriter")
        self.add_menu.setFont(font)
        self.add_menu.setObjectName("add_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.create_file = QtWidgets.QAction(MainWindow)
        self.create_file.setObjectName("create_file")
        self.export_file = QtWidgets.QAction(MainWindow)
        self.export_file.setObjectName("export_file")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.delete_track = QtWidgets.QAction(MainWindow)
        self.delete_track.setObjectName("delete_track")
        self.add_from_spoty = QtWidgets.QAction(MainWindow)
        self.add_from_spoty.setObjectName("add_from_spoty")
        self.add_from_disk = QtWidgets.QAction(MainWindow)
        self.add_from_disk.setObjectName("add_from_disk")
        self.add_from_youtube = QtWidgets.QAction(MainWindow)
        self.add_from_youtube.setObjectName("add_from_youtube")
        self.import_file = QtWidgets.QAction(MainWindow)
        self.import_file.setObjectName("import_file")
        self.change_playlist = QtWidgets.QAction(MainWindow)
        self.change_playlist.setObjectName("change_playlist")
        self.add_from_disk_2 = QtWidgets.QAction(MainWindow)
        self.add_from_disk_2.setObjectName("add_from_disk_2")
        self.delete_playlist = QtWidgets.QAction(MainWindow)
        self.delete_playlist.setObjectName("delete_playlist")
        self.add_from_disk_3 = QtWidgets.QAction(MainWindow)
        self.add_from_disk_3.setObjectName("add_from_disk_3")
        self.playlist_menu.addAction(self.create_file)
        self.playlist_menu.addAction(self.change_playlist)
        self.playlist_menu.addSeparator()
        self.playlist_menu.addAction(self.delete_playlist)
        self.add_menu.addAction(self.add_from_spoty)
        self.add_menu.addAction(self.add_from_youtube)
        self.add_menu.addAction(self.add_from_disk_3)
        self.track_menu.addAction(self.add_menu.menuAction())
        self.track_menu.addSeparator()
        self.track_menu.addAction(self.delete_track)
        self.menubar.addAction(self.playlist_menu.menuAction())
        self.menubar.addAction(self.track_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Botify"))
        self.pause_btn.setText(_translate("MainWindow", "||"))
        self.previous_btn.setText(_translate("MainWindow", "ᐊᐊ"))
        self.play_btn.setText(_translate("MainWindow", "ᐅ"))
        self.next_btn.setText(_translate("MainWindow", "ᐅᐅ"))
        self.get_track.setText(_translate("MainWindow", "Открыть"))
        self.playlist_menu.setTitle(_translate("MainWindow", "Плейлист"))
        self.track_menu.setTitle(_translate("MainWindow", "Трек"))
        self.add_menu.setTitle(_translate("MainWindow", "Добавить"))
        self.create_file.setText(_translate("MainWindow", "Создать"))
        self.export_file.setText(_translate("MainWindow", "Экспортировать"))
        self.action.setText(_translate("MainWindow", "Добавить из файла"))
        self.delete_track.setText(_translate("MainWindow", "Удалить"))
        self.add_from_spoty.setText(_translate("MainWindow", "из Spotify"))
        self.add_from_disk.setText(_translate("MainWindow", "с диска"))
        self.add_from_youtube.setText(_translate("MainWindow", "из Youtube"))
        self.import_file.setText(_translate("MainWindow", "Импортировать"))
        self.change_playlist.setText(_translate("MainWindow", "Переключить"))
        self.add_from_disk_2.setText(_translate("MainWindow", "с диска"))
        self.delete_playlist.setText(_translate("MainWindow", "Удалить"))
        self.add_from_disk_3.setText(_translate("MainWindow", "с диска"))
